name: test_cli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  http: ^1.2.0
  lottie: 3.1.2
  get_storage: 2.1.1
  just_audio: 0.9.38
  sqflite: 2.3.3+1
  path_provider: 2.1.3
  scroll_to_index: 3.0.1
  carousel_slider: 4.2.1
  url_launcher: 6.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/icon/icon.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
    - assets/images/menulis_logo.png
    - assets/images/hafalan_logo.png
    - assets/images/afirmasi_logo.png
    - assets/images/alquran_logo.png
    - assets/images/murottal_logo.png
    - assets/icon/
  uses-material-design: true

